---
inherit: base.yml
applications:
- name: crime-data-explorer
  host: crime-data-explorer
  buildpack: nodejs_buildpack
  memory: 512M
  domain: fr.cloud.gov
env:
  CDE_API: 'https://api.usa.gov/crime/fbi/ucr'
services:
  - crime-data-api-key-production
